[[mutable_areas]]
cap_list = ["Z", "X", "C", "V"]
pos_list = [20, 21, 22, 23]

[[pinned_keys]]
cap = ","
pos = 27

[[pinned_keys]]
cap = "."
pos = 28

[[pinned_keys]]
cap = "/"
pos = 29

[[pinned_keys]]
cap = ";"
pos = 9
