[key_cost]
hit_efforts = [
    9, 5, 3, 6, 7, 9, 6, 3, 5, 9,
    1, 0, 0, 0, 5, 5, 0, 0, 0, 1,
    8, 8, 6, 4, 9, 6, 4, 6, 8, 8,
]
max_finger_usage = [
    0.12, 0.16, 0.20, 0.22, inf, inf, 0.22, 0.20, 0.16, 0.12
]
max_hand_usage_imbalance = 0.025
similarity_score = [
    1.0, 0.8, 0.3
]

[dis_cost]
coordinates = [
    [0.00, 0.00], [1.00, 0.00], [2.00, 0.00], [3.00, 0.00], [4.00, 0.00],
    [5.00, 0.00], [6.00, 0.00], [7.00, 0.00], [8.00, 0.00], [9.00, 0.00],
    [0.25, 1.00], [1.25, 1.00], [2.25, 1.00], [3.25, 1.00], [4.25, 1.00],
    [5.25, 1.00], [6.25, 1.00], [7.25, 1.00], [8.25, 1.00], [9.25, 1.00],
    [0.75, 2.00], [1.75, 2.00], [2.75, 2.00], [3.75, 2.00], [4.75, 2.00],
    [5.75, 2.00], [6.75, 2.00], [7.75, 2.00], [8.75, 2.00], [9.75, 2.00],
]
fingering = [
    0, 1, 2, 3, 3, 6, 6, 7, 8, 9,
    0, 1, 2, 3, 3, 6, 6, 7, 8, 9,
    0, 1, 2, 3, 3, 6, 6, 7, 8, 9,
]
base_keys = [
    10, 11, 12, 13, -1, -1, 16, 17, 18, 19
]
move_efforts = [
    1.20, 1.15, 1.05, 1.00, inf, inf, 1.00, 1.15, 1.20, 1.25
]
max_finger_usage = [
    0.10, 0.16, 0.25, 0.25, inf, inf, 0.25, 0.25, 0.16, 0.10
]
max_hand_usage_imbalance = 0.050


[seq_cost]
top_ngram = 10
bad_allowed = 1
cost_of_pain_level = [
    0.0, 1.0, 2.0, 4.0, 8.0
]
pain_levels = [
    [#  # (0, 0): Q
        4, 3, 2, 1, 1, 0, 0, 0, 0, 0,
        4, 4, 3, 2, 1, 0, 0, 0, 0, 0,
        4, 4, 4, 2, 2, 0, 0, 0, 0, 0,
    ], [# (0, 1): W
        3, 4, 1, 1, 1, 0, 0, 0, 0, 0,
        2, 4, 2, 1, 1, 0, 0, 0, 0, 0,
        4, 4, 3, 2, 3, 0, 0, 0, 0, 0,
    ], [# (0, 2): E
        2, 1, 2, 1, 1, 0, 0, 0, 0, 0,
        2, 3, 4, 0, 2, 0, 0, 0, 0, 0,
        4, 4, 4, 3, 4, 0, 0, 0, 0, 0,
    ], [# (0, 3): R
        1, 1, 1, 2, 3, 0, 0, 0, 0, 0,
        2, 2, 4, 3, 3, 0, 0, 0, 0, 0,
        4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
    ], [# (0, 4): T
        1, 1, 2, 4, 3, 0, 0, 0, 0, 0,
        2, 2, 3, 4, 4, 0, 0, 0, 0, 0,
        4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
    ], [# (0, 5): Y
        0, 0, 0, 0, 0, 4, 4, 3, 2, 1,
        0, 0, 0, 0, 0, 4, 4, 3, 2, 2,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
    ], [# (0, 6): U
        0, 0, 0, 0, 0, 4, 2, 1, 1, 1,
        0, 0, 0, 0, 0, 4, 3, 2, 2, 2,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
    ], [# (0, 7): I
        0, 0, 0, 0, 0, 3, 1, 2, 1, 2,
        0, 0, 0, 0, 0, 1, 1, 4, 2, 2,
        0, 0, 0, 0, 0, 3, 4, 4, 4, 4,
    ], [# (0, 8): O
        0, 0, 0, 0, 0, 2, 2, 1, 2, 3,
        0, 0, 0, 0, 0, 1, 1, 3, 4, 3,
        0, 0, 0, 0, 0, 2, 4, 4, 4, 4,
    ], [# (0, 9): P
        0, 0, 0, 0, 0, 1, 1, 2, 2, 4,
        0, 0, 0, 0, 0, 2, 2, 3, 4, 4,
        0, 0, 0, 0, 0, 3, 4, 4, 4, 4,
    ], [# (1, 0): A
        4, 2, 2, 2, 2, 0, 0, 0, 0, 0,
        4, 2, 2, 1, 1, 0, 0, 0, 0, 0,
        4, 4, 3, 1, 2, 0, 0, 0, 0, 0,
    ], [# (1, 1): S
        4, 4, 2, 2, 2, 0, 0, 0, 0, 0,
        2, 4, 0, 1, 1, 0, 0, 0, 0, 0,
        4, 4, 4, 2, 2, 0, 0, 0, 0, 0,
    ], [# (1, 2): D
        3, 2, 4, 2, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 2, 0, 0, 0, 0, 0,
        2, 4, 4, 2, 3, 0, 0, 0, 0, 0,
    ], [# (1, 3): F
        0, 1, 1, 4, 4, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 4, 0, 0, 0, 0, 0,
        3, 3, 4, 4, 4, 0, 0, 0, 0, 0,
    ], [# (1, 4): G
        2, 2, 2, 4, 4, 0, 0, 0, 0, 0,
        1, 1, 2, 4, 3, 0, 0, 0, 0, 0,
        2, 3, 4, 4, 4, 0, 0, 0, 0, 0,
    ], [# (1, 5): H
        0, 0, 0, 0, 0, 4, 4, 2, 2, 2,
        0, 0, 0, 0, 0, 3, 4, 2, 1, 1,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
    ], [# (1, 6): J
        0, 0, 0, 0, 0, 4, 2, 1, 1, 1,
        0, 0, 0, 0, 0, 4, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 3, 4, 3, 2,
    ], [# (1, 7): K
        0, 0, 0, 0, 0, 4, 2, 4, 2, 3,
        0, 0, 0, 0, 0, 2, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 2, 4, 3, 2,
    ], [# (1, 8): L
        0, 0, 0, 0, 0, 4, 2, 1, 4, 4,
        0, 0, 0, 0, 0, 1, 1, 0, 4, 2,
        0, 0, 0, 0, 0, 1, 2, 3, 4, 3,
    ], [# (1, 9): ;
        0, 0, 0, 0, 0, 4, 1, 1, 1, 4,
        0, 0, 0, 0, 0, 1, 1, 1, 2, 4,
        0, 0, 0, 0, 0, 1, 2, 4, 4, 4,
    ], [# (2, 0): Z
        4, 4, 3, 3, 3, 0, 0, 0, 0, 0,
        4, 4, 3, 2, 2, 0, 0, 0, 0, 0,
        4, 4, 2, 1, 2, 0, 0, 0, 0, 0,
    ], [# (2, 1): X
        4, 4, 4, 4, 3, 0, 0, 0, 0, 0,
        4, 4, 4, 3, 2, 0, 0, 0, 0, 0,
        4, 4, 1, 1, 2, 0, 0, 0, 0, 0,
    ], [# (2, 2): C
        4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
        3, 4, 4, 3, 3, 0, 0, 0, 0, 0,
        3, 2, 3, 2, 2, 0, 0, 0, 0, 0,
    ], [# (2, 3): V
        3, 3, 3, 4, 4, 0, 0, 0, 0, 0,
        1, 1, 1, 4, 4, 0, 0, 0, 0, 0,
        2, 2, 2, 4, 4, 0, 0, 0, 0, 0,
    ], [# (2, 4): B
        4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
        1, 2, 3, 4, 4, 0, 0, 0, 0, 0,
        2, 2, 3, 4, 4, 0, 0, 0, 0, 0,
    ], [# (2, 5): N
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
        0, 0, 0, 0, 0, 4, 4, 2, 1, 1,
        0, 0, 0, 0, 0, 4, 3, 3, 2, 3,
    ], [# (2, 6): M
        0, 0, 0, 0, 0, 4, 4, 4, 3, 4,
        0, 0, 0, 0, 0, 4, 4, 1, 1, 1,
        0, 0, 0, 0, 0, 4, 3, 1, 1, 2,
    ], [# (2, 7): ,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
        0, 0, 0, 0, 0, 4, 2, 4, 3, 3,
        0, 0, 0, 0, 0, 2, 1, 3, 1, 2,
    ], [# (2, 8): .
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
        0, 0, 0, 0, 0, 4, 2, 2, 4, 4,
        0, 0, 0, 0, 0, 2, 1, 1, 4, 2,
    ], [# (2, 9): /
        0, 0, 0, 0, 0, 3, 3, 3, 4, 4,
        0, 0, 0, 0, 0, 2, 2, 2, 2, 4,
        0, 0, 0, 0, 0, 1, 1, 2, 3, 4,
    ],
]
