[key_cost]
# 击键的代价
key_costs = [
    9, 5, 3, 6, 7, 9, 6, 3, 5, 9,
    1, 0, 0, 0, 5, 5, 0, 0, 0, 1,
    8, 8, 6, 4, 9, 6, 4, 6, 8, 8,
]
# 相似度分数
similarity_scores = [
    1.0, 0.8, 0.3
]

[dis_cost]
# 按键横纵坐标
coordinates = [
    [0.00, 0.00], [1.00, 0.00], [2.00, 0.00], [3.00, 0.00], [4.00, 0.00],
    [5.00, 0.00], [6.00, 0.00], [7.00, 0.00], [8.00, 0.00], [9.00, 0.00],
    [0.25, 1.00], [1.25, 1.00], [2.25, 1.00], [3.25, 1.00], [4.25, 1.00],
    [5.25, 1.00], [6.25, 1.00], [7.25, 1.00], [8.25, 1.00], [9.25, 1.00],
    [0.75, 2.00], [1.75, 2.00], [2.75, 2.00], [3.75, 2.00], [4.75, 2.00],
    [5.75, 2.00], [6.75, 2.00], [7.75, 2.00], [8.75, 2.00], [9.75, 2.00],
]

[seq_cost]
# 不适程度对应的代价
cost_of_pain_levels = [
    0, 1, 2, 4, 8
]
# 组合的不适程度
pain_levels = [
    [#  # start with Q
        4, 3, 2, 1, 1, 0, 0, 0, 0, 0,
        4, 4, 3, 2, 1, 0, 0, 0, 0, 0,
        4, 4, 4, 2, 2, 0, 0, 0, 0, 0,
    ], [# start with W
        3, 4, 1, 1, 1, 0, 0, 0, 0, 0,
        2, 4, 2, 1, 1, 0, 0, 0, 0, 0,
        4, 4, 3, 2, 3, 0, 0, 0, 0, 0,
    ], [# start with E
        2, 1, 2, 1, 1, 0, 0, 0, 0, 0,
        2, 3, 4, 0, 2, 0, 0, 0, 0, 0,
        4, 4, 4, 3, 4, 0, 0, 0, 0, 0,
    ], [# start with R
        1, 1, 1, 2, 3, 0, 0, 0, 0, 0,
        2, 2, 4, 3, 3, 0, 0, 0, 0, 0,
        4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
    ], [# start with T
        1, 1, 2, 4, 3, 0, 0, 0, 0, 0,
        2, 2, 3, 4, 4, 0, 0, 0, 0, 0,
        4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
    ], [# start with Y
        0, 0, 0, 0, 0, 4, 4, 3, 2, 1,
        0, 0, 0, 0, 0, 4, 4, 3, 2, 2,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
    ], [# start with U
        0, 0, 0, 0, 0, 4, 2, 1, 1, 1,
        0, 0, 0, 0, 0, 4, 3, 2, 2, 2,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
    ], [# start with I
        0, 0, 0, 0, 0, 3, 1, 2, 1, 2,
        0, 0, 0, 0, 0, 1, 1, 4, 2, 2,
        0, 0, 0, 0, 0, 3, 4, 4, 4, 4,
    ], [# start with O
        0, 0, 0, 0, 0, 2, 2, 1, 2, 3,
        0, 0, 0, 0, 0, 1, 1, 3, 4, 3,
        0, 0, 0, 0, 0, 2, 4, 4, 4, 4,
    ], [# start with P
        0, 0, 0, 0, 0, 1, 1, 2, 2, 4,
        0, 0, 0, 0, 0, 2, 2, 3, 4, 4,
        0, 0, 0, 0, 0, 3, 4, 4, 4, 4,
    ], [# start with A
        4, 2, 2, 2, 2, 0, 0, 0, 0, 0,
        4, 2, 2, 1, 1, 0, 0, 0, 0, 0,
        4, 4, 3, 1, 2, 0, 0, 0, 0, 0,
    ], [# start with S
        4, 4, 2, 2, 2, 0, 0, 0, 0, 0,
        2, 4, 0, 1, 1, 0, 0, 0, 0, 0,
        4, 4, 4, 2, 2, 0, 0, 0, 0, 0,
    ], [# start with D
        3, 2, 4, 2, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 2, 0, 0, 0, 0, 0,
        2, 4, 4, 2, 3, 0, 0, 0, 0, 0,
    ], [# start with F
        0, 1, 1, 4, 4, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 4, 0, 0, 0, 0, 0,
        3, 3, 4, 4, 4, 0, 0, 0, 0, 0,
    ], [# start with G
        2, 2, 2, 4, 4, 0, 0, 0, 0, 0,
        1, 1, 2, 4, 3, 0, 0, 0, 0, 0,
        2, 3, 4, 4, 4, 0, 0, 0, 0, 0,
    ], [# start with H
        0, 0, 0, 0, 0, 4, 4, 2, 2, 2,
        0, 0, 0, 0, 0, 3, 4, 2, 1, 1,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
    ], [# start with J
        0, 0, 0, 0, 0, 4, 2, 1, 1, 1,
        0, 0, 0, 0, 0, 4, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 3, 4, 3, 2,
    ], [# start with K
        0, 0, 0, 0, 0, 4, 2, 4, 2, 3,
        0, 0, 0, 0, 0, 2, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 2, 4, 3, 2,
    ], [# start with L
        0, 0, 0, 0, 0, 4, 2, 1, 4, 4,
        0, 0, 0, 0, 0, 1, 1, 0, 4, 2,
        0, 0, 0, 0, 0, 1, 2, 3, 4, 3,
    ], [# start with ;
        0, 0, 0, 0, 0, 4, 1, 1, 1, 4,
        0, 0, 0, 0, 0, 1, 1, 1, 2, 4,
        0, 0, 0, 0, 0, 1, 2, 4, 4, 4,
    ], [# start with Z
        4, 4, 3, 3, 3, 0, 0, 0, 0, 0,
        4, 4, 3, 2, 2, 0, 0, 0, 0, 0,
        4, 4, 2, 1, 2, 0, 0, 0, 0, 0,
    ], [# start with X
        4, 4, 4, 4, 3, 0, 0, 0, 0, 0,
        4, 4, 4, 3, 2, 0, 0, 0, 0, 0,
        4, 4, 1, 1, 2, 0, 0, 0, 0, 0,
    ], [# start with C
        4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
        3, 4, 4, 3, 3, 0, 0, 0, 0, 0,
        3, 2, 3, 2, 2, 0, 0, 0, 0, 0,
    ], [# start with V
        3, 3, 3, 4, 4, 0, 0, 0, 0, 0,
        1, 1, 1, 4, 4, 0, 0, 0, 0, 0,
        2, 2, 2, 4, 4, 0, 0, 0, 0, 0,
    ], [# start with B
        4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
        1, 2, 3, 4, 4, 0, 0, 0, 0, 0,
        2, 2, 3, 4, 4, 0, 0, 0, 0, 0,
    ], [# start with N
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
        0, 0, 0, 0, 0, 4, 4, 2, 1, 1,
        0, 0, 0, 0, 0, 4, 3, 3, 2, 3,
    ], [# start with M
        0, 0, 0, 0, 0, 4, 4, 4, 3, 4,
        0, 0, 0, 0, 0, 4, 4, 1, 1, 1,
        0, 0, 0, 0, 0, 4, 3, 1, 1, 2,
    ], [# start with ,
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
        0, 0, 0, 0, 0, 4, 2, 4, 3, 3,
        0, 0, 0, 0, 0, 2, 1, 3, 1, 2,
    ], [# start with .
        0, 0, 0, 0, 0, 4, 4, 4, 4, 4,
        0, 0, 0, 0, 0, 4, 2, 2, 4, 4,
        0, 0, 0, 0, 0, 2, 1, 1, 4, 2,
    ], [# start with /
        0, 0, 0, 0, 0, 3, 3, 3, 4, 4,
        0, 0, 0, 0, 0, 2, 2, 2, 2, 4,
        0, 0, 0, 0, 0, 1, 1, 2, 3, 4,
    ],
]
